import vcr
from pathlib import Path
from sure import scenario
from berlin_bike_watch import Scraper


my_vcr = vcr.VCR(
    serializer="yaml",
    cassette_library_dir=str(Path(__file__).parent.joinpath("cassettes")),
    # record_mode='all',
    match_on=["uri", "method", "path", "query"],
)


def prepare_scraper(scenario):
    # creates a scraper that points to the page with male bikes found
    scenario.scraper = Scraper(
        "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/"
    )


with_scraper = scenario(prepare_scraper)


@my_vcr.use_cassette
@with_scraper
def test_scrape_first_page(test):
    "Scraper#scrape(url) should scrape the data from the first page"

    results = test.scraper.run()

    results.should.equal(
        [
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.759671.php",
                "description": "Metallicgraues Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181116-0530-318740",
                "kind_of_bike": "Herrenrad/ Rennrad",
                "manufacturer": "Cube",
                "model": "Streamer",
                "color": "metallicgrau",
                "department": "Direktion 4 Abschnitt 41",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.759659.php",
                "description": "Schwarzes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181114-1130-262343",
                "kind_of_bike": "Mountainbike",
                "manufacturer": "unbekannt",
                "model": "schwarz",
                "color": "Direktion 4 Abschnitt 41",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758854.php",
                "description": "Schwarzes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Triumpf",
                "model": "1306",
                "color": "schwarz",
                "department": "Direktion 5 Abschnitt 55",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758846.php",
                "description": "Schwarzes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Frosch",
                "model": "schwarz",
                "color": "Direktion 5 Abschnitt 55",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758827.php",
                "description": "Blaues Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181030-1502-019502",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Giant",
                "model": "blau",
                "color": "Direktion 2 Abschnitt 25",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758768.php",
                "description": "Blau-weißes Mountainbike",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181030-1502-019502",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Tecnobike",
                "model": "Rubino",
                "color": "Blau-weiß",
                "department": "Direktion 2 Abschnitt 25",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758590.php",
                "description": "Silberfarbenes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "180220-0300-250866",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "unbekannt",
                "model": "Mountainbike",
                "color": "silberfarben",
                "department": "Direktion 5 Abschnitt 51",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758541.php",
                "description": "Silbergraues Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181109-0725-020897",
                "kind_of_bike": "Herrnfahrrad",
                "manufacturer": "unbekannt",
                "model": "Trekkingrad",
                "color": "silbergrau",
                "department": "Direktion 1 Abschnitt 16",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758524.php",
                "description": "Blaues Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181109-0730-020897",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Schwinn",
                "model": "Rennrad",
                "color": "blau",
                "department": "Direktion 1 Abschnitt 16",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758520.php",
                "description": "Schwarzes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181109-0730-020897",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Bergamont",
                "model": "Trekkingrad",
                "color": "schwarz",
                "department": "Direktion 1 Abschnitt 16",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758507.php",
                "description": "Weißes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181109-0730-020897",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Focus",
                "model": "Trekkingad",
                "color": "weiß",
                "department": "Direktion 1 Abschnitt 16",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758499.php",
                "description": "Schwarzes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181109-0540-020897",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Hanseatic",
                "model": "Trekkingrad",
                "color": "schwarz",
                "department": "Direktion 1 Abschnitt 16",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758491.php",
                "description": "Anthrazitfarbenes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181109-0540-020897",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Winora",
                "model": "Trekkingrad",
                "color": "amthrazit",
                "department": "Direktion 1 Abschnitt 16",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758485.php",
                "description": "Schwarzes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181109-0540-020897",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "unbekannt",
                "model": "Rennrad",
                "color": "schwarz",
                "department": "Direktion 1 Abschnitt 16",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758483.php",
                "description": "Schwarzes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181109-0540-020897",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Checkerpig",
                "model": "Trekkingrad",
                "color": "schwarz",
                "department": "Direktion 1 Abschnitt 16",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758479.php",
                "description": "Grünes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181109-0540-020897",
                "kind_of_bike": "Herrenrad",
                "manufacturer": "Müllerin / Forelle",
                "model": "Rennrad",
                "color": "grün",
                "department": "Direktion 1 Abschnitt 16",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758465.php",
                "description": "Violettes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181109-0540-020897",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Peugeot",
                "model": "violett",
                "color": "Direktion 1 Abschnitt 16",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758458.php",
                "description": "Grün-silbernes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181109-0540-020897",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Diamant",
                "model": "Tourenrad",
                "color": "grün-silber",
                "department": "Direktion 1 Abschnitt 16",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758457.php",
                "description": "Silberfarbenes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181109-0540-020897",
                "kind_of_bike": "Herrenfahrrad",
                "model": "Tourenrad",
                "color": "silberfarben",
                "department": "Direktion 1 Abschnitt 16",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758449.php",
                "description": "Silberfarbenes Mountainbike",
                "operation_number": "181109-0540-020897",
                "kind_of_bike": "Mountainbike",
                "manufacturer": "Terrago / Giant",
                "model": "Trekkingrad",
                "color": "silber",
                "department": "Direktion 1 Abschnitt 16",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758439.php",
                "description": "Schwarzes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181109-0540-020897",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "unbekannt",
                "model": "Trekkingrad",
                "color": "schwarz",
                "department": "Direktion 1 Abschnitt 16",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.758000.php",
                "description": "Graues Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "180907-1515-037209",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Tecnobike",
                "model": "Dasistmeinrad",
                "color": "Grau",
                "department": "Direktion 5 Abschnitt 51",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.757263.php",
                "description": "Rotes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181014-0325-339615",
                "kind_of_bike": "Herrenfahrrad / Rennrad",
                "manufacturer": "Chrisson",
                "model": "FG Flat 1.0",
                "color": "rot",
                "department": "Direktion 3 Abschnitt 34",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.756596.php",
                "description": "Blau-weißes Rennrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "180721-1000-310282",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Giant",
                "model": "Peloton",
                "color": "Blau-weiß",
                "department": "Direktion 5 Abschnitt 52",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.756571.php",
                "description": "Silbernes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181029-1239-226092",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Rixe",
                "model": "Silber",
                "color": "Direktion 2 Abschnitt 21",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.754881.php",
                "description": "Blaues Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "180928-0700-019814",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Calvin",
                "model": "blau",
                "color": "Direktion 3 Abschnitt 34",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.754867.php",
                "description": "Blaues Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "180928-0810-031594",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Gazelle",
                "model": "blau",
                "color": "Direktion 3 Abschnitt 34",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.754850.php",
                "description": "Schwarzes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181030-1150-333474",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Triumph",
                "model": "PS331",
                "color": "schwarz",
                "department": "Direktion 2 Abschnitt 24",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.754546.php",
                "description": "Chrom-silberfarbenes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181011-1515-036724",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "unbekannt",
                "model": "Chrom/silber",
                "color": "Direktion 6 Abschnitt 66",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.754534.php",
                "description": "Blaues Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181011-1515-036724",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Tourrex",
                "model": "blau",
                "color": "Direktion 6 Abschnitt 66",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.754105.php",
                "description": "Blaues Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181029-1400-274057",
                "kind_of_bike": "Herrenharrad",
                "manufacturer": "Trekking",
                "model": "blau",
                "color": "Direktion 4 Abschnitt 41",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.754104.php",
                "description": "Rotes Herrenfahrrad",
                "operation_number": "181001-1143-027370",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "X-Rixe",
                "model": "Comsxs3’OFs",
                "color": "Rot",
                "department": "Direktion 3 Abschnitt 32",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.754049.php",
                "description": "Weiß-schwarzes Herrenfahrrad",
                "operation_number": "181001-1143-027370",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Weiß-schwarz",
                "model": "Direktion 3 Abschnitt 32",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.754035.php",
                "description": "Silbernes Herrenfahrrad",
                "operation_number": "181001-1143-027370",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Hercules",
                "model": "Trekking X24",
                "color": "Silber",
                "department": "Direktion 3 Abschnitt 32",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.754032.php",
                "description": "Weißes Rennrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181101-0910-030315",
                "kind_of_bike": "Rennrad",
                "manufacturer": "Diamant",
                "model": "weiß",
                "color": "Direktion 6 Abschnitt 64",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.754026.php",
                "description": "Schwarzes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181001-1143-027370",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Exclusiv Trekking",
                "model": "ZeitOnline",
                "color": "schwarz",
                "department": "Direktion 3 Abschnitt 32",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.753968.php",
                "description": "Schwarzes Herrenfahrrad",
                "operation_number": "181001-1143-027370",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Triumph",
                "model": "Kulturrad",
                "color": "Schwarz",
                "department": "Direktion 3 Abschnitt 32",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.753963.php",
                "description": "Grau-grünes Mountainbike",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181003-0931-026523",
                "kind_of_bike": "Mountainbike",
                "manufacturer": "Yazoo",
                "model": "Yazoo S 3.6.",
                "color": "grau * grün",
                "department": "Direktion 1 Abschnitt 11",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.753937.php",
                "description": "Schwarzes Herrenfahrrad",
                "operation_number": "181001-1143-027370",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Schwarz",
                "model": "Direktion 3 Abschnitt 32",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.753923.php",
                "description": "Silber-blaues Herrenfahrrad",
                "operation_number": "181001-1143-027370",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Hercules",
                "model": "Silber-Blau",
                "color": "Direktion 3 Abschnitt 32",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.753905.php",
                "description": "Blau-silbernes Herrenfahrrad",
                "operation_number": "181001-1143-027370",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Blau-Silber",
                "model": "Direktion 3 Abschnitt 32",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.753739.php",
                "description": "Grau-metallicfarbenes Herrenrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181028-1455-269290",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Merida",
                "model": "Freeway 9300",
                "color": "grau-metallic",
                "department": "Direktion 3 Abschnitt 36",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.753730.php",
                "description": "Metallicblaues Mountainbike",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "170809-1845-267891",
                "kind_of_bike": "Mountainbike",
                "manufacturer": "Wheeler",
                "model": "Ride 900ZX",
                "color": "metallicblau",
                "department": "Direktion 3 Abschnitt 36",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.753724.php",
                "description": "Rot-silbernes Mountainbike",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "170310-1030-263345",
                "kind_of_bike": "Mountainbike",
                "model": "Special Concept",
                "color": "rot-silber",
                "department": "Direktion 3 Abschnitt 36",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.753698.php",
                "description": "Blaues Mountainbike",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "180323-2100-263302",
                "kind_of_bike": "Mountainbike",
                "manufacturer": "Torrek",
                "model": "m8.nx",
                "color": "blau",
                "department": "Direktion 3 Abschnitt 36",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.753614.php",
                "description": "Schwarzes Mountainbike",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181021-0200-030595",
                "kind_of_bike": "Mountainbike",
                "manufacturer": "Focus",
                "model": "Arriba",
                "color": "schwarz",
                "department": "Direktion 6 Abschnitt 65",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.753520.php",
                "description": "Schwarzes Mountainbike",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "180717-1520-024695",
                "kind_of_bike": "Mountainbike",
                "manufacturer": "Kalkhoff",
                "model": "Track 4.0",
                "color": "schwarz",
                "department": "Direktion 1 K 2 EG Velo",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.753504.php",
                "description": "Schwarzes Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "180717-1520-024695",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Cube",
                "model": "Town",
                "color": "schwarz",
                "department": "Direktion 1 K 2 EG Velo",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.753489.php",
                "description": "Graues Herrenfahrrad",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "181012-0730-331965",
                "kind_of_bike": "Herrenfahrrad",
                "manufacturer": "Cycle Union GmbH",
                "model": "T500",
                "color": "mattgrau",
                "department": "Direktion 3 Abschnitt 33",
            },
            {
                "url": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/artikel.753130.php",
                "description": "Schwarzes Mountainbike",
                "image": "https://www.berlin.de/polizei/service/vermissen-sie-ihr-fahrrad/herrenfahrraeder/",
                "operation_number": "180717-1520-024695",
                "kind_of_bike": "Mountainbike",
                "manufacturer": "Tecnobike",
                "model": "1026",
                "color": "schwarz/ weiß",
                "department": "Direktion 1 K2 EG Velo",
            },
        ]
    )
